import Lddec

l1=Lddec.Lddec()
l1.inserirInicio('E')
l1.inserirInicio('D')
l1.inserirInicio('C')
l1.inserirInicio('B')
l1.inserirInicio('A')
l1.show()
print('------------------')
l1.showReverse()
print('-------Inserindo Z Antes do A---------')
l1.inserirAntesDe('Z','A')
l1.show()
print('------------------')
l1.showReverse()
print('-------Inserindo X Antes do B---------')
l1.inserirAntesDe('X','B')
l1.show()
print('------------------')
l1.showReverse()
print('-------Inserindo Y Antes do C---------')
l1.inserirAntesDe('Y','C')
l1.show()
print('------------------')
l1.showReverse()
print('-------Inserindo V Antes do D---------')
l1.inserirAntesDe('V','D')
l1.show()
print('------------------')
l1.showReverse()
print('-------Inserindo T Antes do E---------')
l1.inserirAntesDe('T','E')
l1.show()
print('------------------')
l1.showReverse()
