import Lddec

l1=Lddec.Lddec()
l1.inserirInicio('D')
l1.inserirInicio('C')
l1.inserirInicio('B')
l1.inserirInicio('A')
l1.inserirFim('E')
l1.inserirFim('F')
l1.inserirFim('G')
l1.inserirFim('H')
l1.show()
print('---------------------------------')
l1.showReverse()
print('---------------------------------')
print('Removendo o A!')
print('---------------------------------')
l1.removerDet('A')
l1.show()
print('---------------------------------')
l1.showReverse()
print('---------------------------------')
print('Removendo o H!')
print('---------------------------------')
l1.removerDet('H')
l1.show()
print('---------------------------------')
l1.showReverse()
print('---------------------------------')
print('Removendo o E!')
print('---------------------------------')
l1.removerDet('E')
l1.show()
print('---------------------------------')
l1.showReverse()
print('---------------------------------')
print('Removendo o G!')
print('---------------------------------')
l1.removerDet('G')
l1.show()
print('---------------------------------')
l1.showReverse()
print('---------------------------------')
print('Removendo o B!')
print('---------------------------------')
l1.removerDet('B')
l1.show()
print('---------------------------------')
l1.showReverse()
print('---------------------------------')
print('Removendo o D!')
print('---------------------------------')
l1.removerDet('D')
l1.show()
print('---------------------------------')
l1.showReverse()
print('---------------------------------')
print('Removendo o C!')
print('---------------------------------')
l1.removerDet('C')
l1.show()
print('---------------------------------')
l1.showReverse()
